file(WRITE ${CASCADE_H}

"////////////////////////////////////////////////////
//Author
//  Peng Xiao <pengxiao@outlook.com>
//
//  This file is automatically generated. Do not edit.
namespace fd
{
"
)

file(APPEND ${CASCADE_H} "const std::string cascade_strings [] = \n{\"")

file(STRINGS ${CASCADE_XML} lines)

message(STATUS "Passing cascade file into header.")

set(count 0)
foreach(line ${lines})
    string(REPLACE "\\" "\\\\" line "${line}")
    string(REPLACE "\"" "\\\"" line "${line}")
    MATH(EXPR count "${count}+1")
    # to avoid static string exceed the string length limit
    if(count EQUAL 1000)
        file(APPEND ${CASCADE_H} "${line}\\n\",\n\"")
        set(count 0)
    else()
        file(APPEND ${CASCADE_H} "${line}\\n\"\n\"")
    endif()
endforeach()

file(APPEND ${CASCADE_H} "\\n\"};\n\n")
file(APPEND ${CASCADE_H} "}\n")
